[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

[features]
# Show the prompt playground
prompt_playground = true

[UI]
# Name of the app and chatbot.
name = "PraisonAI"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]

    [UI.theme.light.primary]

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]

    [UI.theme.dark.primary]


[meta]
generated_by = "1.3.0"
